### ISSUE TITLE
Stack overflow with Custom Spec

### ISSUE THREAD

**Issue by suitcasenuke** [navozenko/LinqSpecs#3]
I've created a custom spec class similar to the "CustomerFromCountrySpec" in the README.md. When I create my custom class, within a second or two I get a stack overflow. 

Here's my class: 

```    
public class CustomSpec: Specification<string>
{
        public string Name { get; set; }

        public CustomSpec(string name)
        {
            Name = name;
        }

        public override Expression<Func<string, bool>> ToExpression()
        {
           return  s => s == Name;
        }
}
```

Here's my test method

```
[Test]
public void CustomClassShouldntStackOverflow()
{
            var s = new CustomSpec("Jose");
            Assert.True(true); //Put a break point here and let it set for 5 seconds, you'll stack overflow.
}
```

**Comment by navozenko** [comment]
Hi, stroebele.
Unfortunately I could not reproduce the issue. Can you give a full example of the project? Which .NET framework? What OS? What version of .NUnit are you using? What VS? What test runner?

**Comment by suitcasenuke** [comment]
I created a PR #4 with a unit test that recreates the issue for me. I wish there was a better way of catching the error.

**Comment by navozenko** [comment]
I can not reproduce the exception. I have run your test with both TestDriven.NET and Microsoft Test Explorer.

And in truth, I generally do not understand where StackoverflowException can comes from when execution is suspendedat the breakpoint, because LinqSpecs is a single-threaded library (threads and tasks are not used). Also Specification class has no constructor and static fields.

Could this be a bug of the test runner you are using? Which runner you are using? May be ReSharper?.. it is very bugged.. Try another test runner please.

And post a complete exception message including a stacktrace please.
Also I ask you to comment line with `var customSpec = new CustomSpec("Jose");` Does exception disappear?

**Comment by suitcasenuke** [comment]
You nailed it, Resharper was the problem. Even using MS Test Explorer would cause a crash, however once Resharper was completely disabled, everything worked fine. Thanks for your help.

**Comment by navozenko** [comment]
OK, thanks.
